import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.preprocessing import StandardScaler

# 1. DATA ACQUISITION

# Sourcing 13 years of historical daily OHLCV data for Reliance Industries
ticker = "RELIANCE.NS"
data = yf.download(ticker, start="2011-01-01", end="2024-01-02")

# 2. FEATURE ENGINEERING (ALPHA GENERATION)
# Transform raw price data into stationary features to capture market dynamics
df = data.copy()

# Log Returns: Standard transformation to make price data stationary
df['Log_Ret'] = np.log(df['Close'] / df['Close'].shift(1))

# Relative Strength Index (RSI): Momentum indicator to identify overbought/oversold conditions
df['RSI'] = 100 - (100 / (1 + df['Log_Ret'].rolling(window=14).apply(
    lambda x: x[x>0].sum() / abs(x[x<0].sum()) if x[x<0].sum() != 0 else 0)))

# Simple Moving Averages: Capturing trend direction and potential support/resistance
df['SMA_20'] = df['Close'].rolling(window=20).mean()
df['SMA_50'] = df['Close'].rolling(window=50).mean()

# Rolling Volatility: Measuring market risk/noise over a 20-day window
df['Volatility'] = df['Log_Ret'].rolling(window=20).std()

# 3. LABELING (TARGET GENERATION)

# Binary Classification: 1 if Close(T+5) > Close(T), else 0
# We shift the logic backward to align current data with future price movement
df['Target'] = (df['Close'].shift(-5) > df['Close']).astype(int)

# Clean dataset: Remove NaNs generated by rolling windows and target shifting
df.dropna(inplace=True)

# 4. CHRONOLOGICAL DATA SPLITTING
# CRITICAL: Preserve time-series order to avoid Look-Ahead Bias
# Training set: 2011-2020 (Learning period)
# Test set: 2021-2024 (Unseen validation period)
train_df = df.loc['2011-01-01':'2020-12-31']
test_df = df.loc['2021-01-01':'2024-01-01']

features = ['Log_Ret', 'RSI', 'SMA_20', 'SMA_50', 'Volatility']
X_train, y_train = train_df[features], train_df['Target']
X_test, y_test = test_df[features], test_df['Target']

# 5. FEATURE SCALING

# Scale only using training stats to prevent future value leakage into the past
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 6. MODEL INITIALIZATION & TRAINING

# Random Forest selected for its ability to handle non-linear relationships and reduce variance
model = RandomForestClassifier(n_estimators=100, random_state=42, max_depth=10)
model.fit(X_train_scaled, y_train)

# ==========================================
# 7. TRADING SIMULATION (BACKTESTING)
# ==========================================
# Translate probabilistic outputs into Long/Short execution logic
test_data = test_df.copy()
test_data['Signal'] = model.predict(X_test_scaled)

initial_capital = 1000000.0 # Initial setup: ₹1,000,000
current_capital = initial_capital
portfolio_values = []

i = 0
while i < len(test_data) - 6:
    signal = test_data['Signal'].iloc[i]
    
    # Entry Rule: Execute trade at the Open of T+1
    # Exit Rule: Close trade at the Close of T+5
    open_t1 = test_data['Open'].iloc[i+1]
    close_t5 = test_data['Close'].iloc[i+5]
    
    if signal == 1: # Bullish signal -> Go Long
        trade_return = (close_t5 / open_t1) - 1
    else: # Bearish signal -> Go Short 
        trade_return = (open_t1 / close_t5) - 1